language: node_js
node_js:
  - 8

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

on:
  branch: master
  tags: true


jobs:
  include:
    - stage: coverall
      script: "npm run coveralls"
    - stage: "NPM publish"
      script: skip
      deploy:
        provider: npm
        email: "leishenghao@126.com"
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true

stages:
  - test
  - coverall
  - name: "NPM publish"
    if: tag IS present
