language: node_js
node_js:
  - 7.2.1

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "npm i -g npm"

on:
  branch: master
  tags: true

after_script:
  - npm run coveralls

jobs:
  include:
    - stage: "NPM publish"
      script: skip
      deploy:
        provider: npm
        email: "leishenghao@126.com"
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
