language: node_js
node_js:
  - 7.2.1

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: "Test"
      branches:
        only: master
      after_script:
        - npm run coveralls

    - stage: "NPM publish"
      on:
        tags: true
      script: skip
      script: echo "Deploying to NPM ..."
      deploy:
        provider: npm
        email: "simonguo.2009@gmail.com"
        api_key: $NPM_AUTH_TOKEN
